//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IP.VD.Solution.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlickrImage
    {
        public int Id { get; set; }
        public string PhotoId { get; set; }
        public string ThumbnailUrl { get; set; }
        public string Title { get; set; }
        public string WebUrl { get; set; }
        public string Description { get; set; }
        public string Locality_Description { get; set; }
        public string Region_Description { get; set; }
        public string OwnerUserId { get; set; }
        public string Tags { get; set; }
        public Nullable<System.DateTime> DatePosted { get; set; }
        public Nullable<System.DateTime> DateTaken { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
    }
}
